### ISSUE TITLE
Mobs appear on opclan land and are unkillable

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#105]
Two ways to prevent this: make it so anyone can kill mobs on opclan land or prevent mobs on opclan land.

**Comment by baronjutter** [comment]
To slightly add to this issue, the problem also exists on normal clans.  For instance I went to visit a friend who has a clan I am not in.  While I was there a zombie appeared and could hurt me, hurt him, but only he could hurt the zombie.

I understand having mob protection within clan territory to prevent people from slaughtering your livestock or favourite horse, but I think hostile mobs should not be protected within clan territories, or at least a toggle in settings.

**Comment by The-Fireplace** [comment]
Yeah, the part where non-member players can't hurt hostile mobs on clan land was intentional. I can add a toggle for that though.
