### ISSUE TITLE
IC2 machine GUI can be turned on during the declaration of war

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#116]
IC2 machine GUI can be turned on during the declaration of war
Forge-1.12.2-2768
SpongeForge-1.12.2-7.1.6-RC3686
You can use the following code to fix the original code
LandProtectionEvents.java
In the RightClickBlock event
`IBlockState targetState = event.getWorld().getBlockState(event.getPos());`
`boolean isRaided = RaidingParties.isRaidedBy(chunkClan, interactingPlayer);`
`else if (isRaided) {
  if (tile){cancelBlockInteraction(event, interactingPlayer, targetState);}
}`
![1234](https://user-images.githubusercontent.com/38318368/61989139-8fa65300-b05d-11e9-837a-41e69168b453.png)

**Comment by The-Fireplace** [comment]
This should be fixed in Clans 1.3. I am aiming to have it released in around 2 weeks.
