### ISSUE TITLE
[Suggestion] List of restricted items to bring to raid

### ISSUE THREAD

**Issue by Ydrec** [The-Fireplace-Minecraft-Mods/Clans#117]
Add a configurable whitelist/blacklist of items which people can/cant bring have in raid. Many mods add things which are pretty cheaty for pvp. Like quantum armor from ic2 or all kinds of fly items which make pvp unplayable. These items would be confiscated if person takes part in raid and he can return them later with /raid retrieve. Also check for these items at intetvals while raid goes so people cant take them out of some extradimensional storage.

**Comment by The-Fireplace** [comment]
Done in Clans 1.4.0
