### ISSUE TITLE
Borderland still exist after unclaim a chunk

### ISSUE THREAD

**Issue by zongitgud** [The-Fireplace-Minecraft-Mods/Clans#119]
Mc version: 1.12.2
Mod version: latest
Borderland still exist after unclaim a chunk either it normal or opclan chunk. Relaunch the game clear all the bad borderland but once i start claiming they start showing up again. Borderland still appear even when i'm set it to false.

**Comment by The-Fireplace** [comment]
FYI @zongitgud , mod version "latest" is never acceptable. Several versions have been released since you posted the issue, so the issue you experienced now was not on "latest". I'm still going to fix it because I know it's a valid issue, but I figured I'd tell you for future reference.

**Comment by The-Fireplace** [comment]
Fixed in Clans 1.4.0
