### ISSUE TITLE
Support Sponge Economic API

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#122]
Hello, can you consider supporting Sponge Economic API in 1.12.2?
I've done this to support Sponge Economic API
I can provide you with the code if I can.
I hope you can provide a custom event API
So I can write an affiliate plug-in based on Sponge intuitively.
Instead of changing your source code
For example:
When a player enters another player's territory triggers the event, my affiliate can inherit the event and deal with some corresponding problems.
![1234](https://user-images.githubusercontent.com/38318368/63968540-94ce4600-cad2-11e9-9551-2bdd7223b045.png)

**Comment by mcqwy** [comment]
Sorry, my English is terrible.
I hope you can understand it.

**Comment by The-Fireplace** [comment]
I'm not entirely sure I understand what you're asking. I already support Sponge's economy API as of Clans 1.3, so Sponge economies should work with it. As for the second part of what you're asking, a custom event API, I've already started on one that will allow addons to be made using Forge or Sponge. It doesn't have many events yet, but if you have some specific ones you want me to add, let me know and I will see what I can do.

**Comment by mcqwy** [comment]
bout Part Two
If you can provide an API interface.
Other developers do some affiliated plug-ins for this mod
Maybe it will increase the heat of this mod.
No new ideas have come to mind yet.
When I have a new idea, I'll submit it it again.

**Comment by mcqwy** [comment]
This Mod is great.
I like it very much

**Comment by The-Fireplace** [comment]
I do have a basic API released with Clans 1.3, and I am working to enhance it in Clans 1.4 when I come up with more functions to add to the API.
