### ISSUE TITLE
NPE in build 1.3.7 on server startup

### ISSUE THREAD

**Issue by kreezxil** [The-Fireplace-Minecraft-Mods/Clans#123]
Issue:  1.12.2-1.3.7 crashes dedicated server Forge 1.12.2 build 2844

Notes:
     NPE

crash report:
http://paste.ubuntu.com/p/nbnyN4mXyX/

fml server latest:
http://paste.ubuntu.com/p/TyHftCSbCj/

**Comment by kreezxil** [comment]
probably related to FORGE BUILD 2844. i will try using 2838.

**Comment by kreezxil** [comment]
build 2838 didn't resolve it. Did you just push the fix to CF?

**Comment by The-Fireplace** [comment]
I'm going to in a minute, looking to see if any of the bugs I've found in my 1.4 development branch happen here as well
