### ISSUE TITLE
Crash when joining a server with Clans on client & server

### ISSUE THREAD

**Issue by Reisai** [The-Fireplace-Minecraft-Mods/Clans#124]
Steps to reproduce: 
1. Run client with clans installed, run server with clans installed.
2. Attempt to login to the server
3. Client crashes, server does not
Client report: [https://pastebin.com/QcwixykE](url)
Server log of join attempt: [https://pastebin.com/M407dVT2](url)
Forge version: 14.23.5.2844
Minecraft version: 1.12.2
Clans version: 1.3.8

**Comment by kreezxil** [comment]
I think this is the same thing

Client crashes but server does not. it's an NPE.

https://paste.dimdev.org/sawekolehe.mccrash

**Comment by kreezxil** [comment]
I don't know what the first guy did, he messed up his links somehow,

here's his crash report: https://pastebin.com/QcwixykE
and server log: https://pastebin.com/M407dVT2

I'm not affiliated with the 1st guy btw

**Comment by kreezxil** [comment]
I looked at his server log, his server log is not a crash but you'll see that.
