### ISSUE TITLE
Problems when trying to disband a clan.

### ISSUE THREAD

**Issue by maxim0p** [The-Fireplace-Minecraft-Mods/Clans#128]
When trying to disband a clan, with no claim land, the error in chat "An unknown error occurred while attempting to perform this command." appears.

When trying to disband a clan with claimed land, the same error appears in chat, and the game crashes aswell.

This was in a single player world, where I was testing the commands, which I don't know if it had to do with it.

Crashlog:
https://pastebin.com/HwS7Neb9

Error in latest.log:
https://pastebin.com/TyxJHBrm

Forge Version: 14.23.5.2838
Mod Version: Clans-1.12.2-1.3.12

**Comment by The-Fireplace** [comment]
Thanks, I'll get it fixed ASAP
