### ISSUE TITLE
MOBS not spawning at all

### ISSUE THREAD

**Issue by Danickar** [The-Fireplace-Minecraft-Mods/Clans#131]
Forge Version: 14.23.5.2838
Mod Version: 1.12.2-1.3.11

Hostile mobs were not spawning anywhere after the opclan claimed land in the world. While the land was clearly labeled as wilderness and might have been 1,000 blocks or more away from any claimed land, nothing would spawn (naturally or manually using spawners).

When I removed the mod from the server everything started spawning perfectly.

**Comment by The-Fireplace** [comment]
Thanks for the report! While I work on a fix, you might be able to avoid
this issue by turning off the config option that prevents mobs from
spawning on claimed land.

**Comment by The-Fireplace** [comment]
I am having difficulty reproducing this issue. Would you mind sharing your config and what you do to reproduce the issue? I tried:
1. Set the config option to protect claimed land form mobs to on/off (I couldn't reproduce the issue either way)
2. Loaded a server with just Clans 1.3.13 on it
3. Checked that mobs properly did/didn't spawn on claimed land, then flew out over 1000 blocks from the claim at night to see if hostile mobs would spawn

**Comment by The-Fireplace** [comment]
Until I can reproduce this issue, I have to assume this is caused by another mod. If you respond with the information I requested, I will reopen the issue.
