### ISSUE TITLE
Feature Request: Dynmap settings enhancement

### ISSUE THREAD

**Issue by Danickar** [The-Fireplace-Minecraft-Mods/Clans#132]
I love the Dynmap integration, however, a lot of what I claimed for the server are hidden areas that I want the players to discover. I had to turn off the Dynmap options because it was showing the players everything.

Would it be possible to add settings for Dynmap displays for the opclan that are different from everyone else's claims?

This might be more difficult than it is worth, and if so I understand.

**Comment by The-Fireplace** [comment]
I've added it to my todo list for #129 .

**Comment by The-Fireplace** [comment]
Done in Clans 1.4.0
