### ISSUE TITLE
Add transport function

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#133]
Hello
Can you add commands that players send to other territories?
TP Territory Like the original TP Player Directive

**Comment by mcqwy** [comment]
Hello, may I add some TP suggestions?
For example:
Add an on / off profile to the TP instruction
Attach a permission to the TP instruction

**Comment by The-Fireplace** [comment]
My plan is to have a `/opclan tp <clan>` command, and it will have its own permission.

**Comment by mcqwy** [comment]
Because my server map is too large.
It may take half an hour or more if the player needs to walk past during the raid
So I need a separate authority.
Thank you very much.

**Comment by The-Fireplace** [comment]
Hmm. Maybe a `/raid tp` command would also be useful, to teleport to the clan home for a raid you're involved in.

**Comment by mcqwy** [comment]
It's also a good idea. /raid tp

**Comment by The-Fireplace** [comment]
The automatic teleport at the start of the raid and the opclan command should be sufficient. Allowing raiders to go back and forth would generally not be beneficial as in a typical setup they can only be outside the target clan's territory for so many seconds before they get removed from the raid.
