### ISSUE TITLE
Switching language problems

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#138]
In 1.12.2-1.4.0
Switching the language to zh_cn doesn't work (tried coding problems)
If you directly rename the zh_cn.lang file to en_us.lang
The following problems will occur
![12345](https://user-images.githubusercontent.com/38318368/67125909-6a724c80-f228-11e9-957c-5074b068b8fb.png)

**Comment by mcqwy** [comment]
Hello, I have solved this problem for you
ClansLanguageMap.java
Your original code is
`private static final ClansLanguageMap fallbackTranslator = new ClansLanguageMap(“en_us”);`
After modification
![12345](https://user-images.githubusercontent.com/38318368/67157625-26cf2e00-f361-11e9-9691-e2f48bf6b38c.png)
The picture part is modified.
To solve the problem

**Comment by The-Fireplace** [comment]
The whole point of the fallback is for messages that haven't been
translated into other languages. The fact that it was using fallback and
not working right gives me an idea of what's wrong though. I'll look into
it when I can.

**Comment by The-Fireplace** [comment]
![image](https://user-images.githubusercontent.com/5914284/67611906-7d72a880-f763-11e9-8d54-f3f4348ee5e8.png)
I just tested this with Clans 1.4.0.
Is this what you were seeing when you tried the help command after switching the language to zh_cn? If so, it is working as intended, there are just missing translations so it shows English.

**Comment by mcqwy** [comment]
No, it's not.
Returns English when command is not allowed.
To determine if this is the case.
I'll test it again.
Please wait a moment.

**Comment by mcqwy** [comment]
It is confirmed that there is no problem with language switching when testing your 1.12.2-1.4.1.

**Comment by mcqwy** [comment]
Thank you very much for your prompt attention
