### ISSUE TITLE
Katon when creating tribe

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#139]
Forge2825
Sponge7.1.6
Clans1.4
There will be a serious jam when filling in Chinese characters when creating tribes
This does not happen when entering English or numbers
In version 1.3, none of this happened.
![584_%6S3W{CCRS~) %`9GU1](https://user-images.githubusercontent.com/38318368/67218954-d12a7c80-f459-11e9-834b-b88359f63f11.png)

**Comment by The-Fireplace** [comment]
I just tested with only Clans 1.4.0 and Forge 2847 and was unable to reproduce the issue. Does this consistently happen when creating a clan with Chinese characters, or was it just that one time? Also, do you have an economy plugin loaded?

**Comment by mcqwy** [comment]
I tested it again today
No similar situation was found.
Sorry for the inconvenience

**Comment by mcqwy** [comment]
If it's an accident, I'll let you know again

**Comment by mcqwy** [comment]
Because the tests I did on my own computer may have been influenced by other factors.
Thank you very much for your prompt answer.
Now it works very well
![123](https://user-images.githubusercontent.com/38318368/67622899-affacf00-f851-11e9-8696-77ba9a0b7fd8.png)
