### ISSUE TITLE
its says no permission

### ISSUE THREAD

**Issue by varnithian97** [The-Fireplace-Minecraft-Mods/Clans#152]
When using the  /clan create  command after install and config, gives the no permission string. Is there really no permissions for the pluggin? I dont see that anywhere.

Currently using LuckPerms

**Comment by The-Fireplace** [comment]
There are permissions, I just haven't posted them to the CurseForge page yet. Use `/lp tree` to check. Ctrl+F and look for `clans`

**Comment by The-Fireplace** [comment]
Update: Permissions have been posted to CurseForge.
