### ISSUE TITLE
Surprise mode, defenders fail

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#154]
Clans-1.5
Only Raiders can spend gold in the configuration file
Although the successful raid can also reward gold coins
1. If the raid cost more gold than the reward, players will not be interested
2. If the raid cost less gold than the reward, players can use it to brush gold
As in question 2, this will cause the server's gold coin system to fail
I hope you can add:
In the raid mode, if the defenders fail, their money will be deducted

**Comment by The-Fireplace** [comment]
If defenders fail, their money should be reduced by the amount that gets rewarded to the raiders.

**Comment by mcqwy** [comment]
Is there such a function now?
I didn't see it at clans.conf

**Comment by The-Fireplace** [comment]
It's not in the config because it is something that always happens, and
there is no reason to turn it off

**Comment by The-Fireplace** [comment]
If you test and this is not happening for some reason, comment on this issue and I will re-open it.
