### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by Phantom775** [The-Fireplace-Minecraft-Mods/Clans#155]
Hi, i've been running a server with 60+ mods for about a week now, and this is the first time i've had an issue with clans mod. taking out this modification fixes the issue, however, this mod is a vital part of the modpack. the issue? we don't really know, it's simply just crashing the server. here's what it says in console; https://gyazo.com/0343a58c690fa8a47dd3461eaf1177ac

**Comment by The-Fireplace** [comment]
StackOverflowError means it's probably running out of memory. You might try setting "connectedClaimCheck" in the config to "quick" to work around this. This method won't use nearly as much memory when doing the claim connection check, but may also cause some clans to run into issues abandoning claims, particularly when the claims are sorted something like the following, where # is a claim, - is wilderness:
```
--------
-######-
-#----#-
-######-
--------
```

**Comment by Phantom775** [comment]
Thanks for your quick reply. i will be editing this and seeing if that fixes it. Since from what you said this isn't at fault of your mod, you can go ahead and close this if you wish.

**Comment by The-Fireplace** [comment]
There is a slight possibility it's my mod's fault, if it somehow went into an infinite loop when checking the claims, but it's more likely that someone finally hit the right number of claims to run it out of memory on the claim check. Let me know how it goes.

**Comment by Phantom775** [comment]
Still not working, then again we only have 8 gigs of RAM. i'll look into getting an upgrade.

**Comment by The-Fireplace** [comment]
And the crash was the same? How much memory is used on average without
Clans?

**Comment by The-Fireplace** [comment]
I would have expected that to fix it, so if it didn't, it might be a bug
with the mod.

**Comment by The-Fireplace** [comment]
Seriously, I wouldn't close this or buy more ram just yet. If you provide the information requested I'm willing to look into it to see if it's a problem with the mod.

**Comment by Phantom775** [comment]
Hey I apologize for the delay. I deleted the chunks folder and that fixed our issue, however, now nether claims overlap into the over world - Atleast on dynmap. I’ve yet to investigate that.

**Comment by The-Fireplace** [comment]
Ok, thanks for the update.

**Comment by Phantom775** [comment]
Also, on server start it’s around 37% memory. Server is on 3 hour restarts.
