### ISSUE TITLE
Unable to lower distance of land claim between borders.

### ISSUE THREAD

**Issue by Methlon** [The-Fireplace-Minecraft-Mods/Clans#163]
**Describe the bug**
I'll admit.. I'm not 100% sure if it's a bug or I can't read.
I created a test clan while trying to configure this mod, and am finding I am unable to claim land closer than 400 blocks from already claimed land (which is a bit extreme lol)

"You cannot claim this chunk of land because it is too close to another clan's home.  Make sure you are at least 400.0 blocks away from other clans' homes before trying again.  Try using /clan fancymap to help determine where other clans are."

I've been up and down the config file, and nothing I've lowered has changed this.  It's always at 400 blocks.  Config is being edited server side, of course.

**To Reproduce**
1. Go outside a border land by 40 plus blocks, as I've set in the config.
2. /clan claim
3. see message.

**Logs/Screenshots/Videos**
Logs have no errors.  Config's just don't seem to lower this value.
My only input in this regard was the error message.

--These are the values I've changed, but I've seen no difference.
  #

   # Prevents other clans from claiming around the edges of a clan's territory. When a chunk of land is between two clans' territories, the first clan to be near it takes precedence.
    B:enableBorderlands=false

    # This multiplied by the minimum clan home distance is how far away from other clans' homes to make the initial claim for a clan.
    # Min: 0.0
    # Max: 1.7976931348623157E308
    D:initialClaimSeparationMultiplier=0.0

    # Minimum number of blocks between clan homes.
    # Min: 0
    # Max: 2147483647
    I:minClanHomeDist=40

    # If enabled, multiplies the max claim count by the number of players in the clan.
    B:multiplyMaxClaimsByPlayers=false

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [1.12.2]
 - Mod Version: [1.5.3]
(I upgraded from 1.5.1 while working on this, noting a new release.)
 - Forge (If applicable) [Forge 1122-14.23.5.2847]
- Using technic launcher.

None the less, it stays demanding 400 blocks.
Is it a bug?  Hard coded this way?  Am I blind?

Thanks, sir.
Appreciate you as always.

**Comment by The-Fireplace** [comment]
Thanks for providing all the details, I'll look into it as soon as possible. Your config looks good, so it most likely is a bug.

**Comment by The-Fireplace** [comment]
Hmm, I'm not sure. I'll look into it some more. I just tested by setting minClanHomeDist to 16 and the initial claim separation multiplier to 0.001 and it seemed to work.

**Comment by Methlon** [comment]
I appreciate you getting back to me on that.
When I'm fresh tomorrow (or at least at my mildest weekend hangover) I'll tweak the settings and see if it works for me, too.  I'm sure it will.  I'll write you back and let'che know.  Simple enough fix if that's the case.

**Comment by The-Fireplace** [comment]
Unfortunately I'm having difficulty reproducing this problem. One question I have to ask is did you restart the server after changing the config options? The only way I see that it would have remained at 400 with those config values is if the server didn't get restarted after you changed it.

**Comment by Methlon** [comment]
Problem still persists for me.. Adjusted the distances same as yours, got the latest version of clans as of 22 hours ago.  Could be a mod conflict, unless there's some way being in multiple clans could mess with it.  (admin clan and test clan).  Dunno..  That's not a week day job picking apart the mods to single out the borken' one.  I'll swing on in that direction and let you know what I find.. Probably this weekend.

Edit: And yes, Every config change comes with a restart of the server.
I've been running them off and on for a pretty good set of years.

I Suppose I could also try deleting it and letting it generate a new config.. maybe something is stored somewhere that I don't know about, and it's just not updating..  Eh, weekend work.
There's sure to be a painfully simple reason why it's doing what it's doing lol.

Thanks for sticking with it.

**Comment by The-Fireplace** [comment]
I don't see how this one could be a mod conflict unless some mod is purposefully interfering with it or is messing with everything that uses annotation-based config. The number shown in the error message pulls directly from the config, so if the number was correct I would expect the math to be wrong. One more question I have for you is if you've changed any other config options and seen the results.

**Comment by Methlon** [comment]
Interesting... I changed claim cost from 200 to 500, and it still costs 200 after modifying the config and restarting the server.   Yes I'm really resetting the server.  /stop, ./run.sh lol.  Twice, in fact... 

I'm about to try letting it gen a new config file, and changing that.
Will reply short, or edit in a reply shortly.

Edit:  Odd.. it did not generate a config after removing it..  Let's try again.
Edit edit:  Now it's generated a config.. Now I'll tweak it.

**Comment by The-Fireplace** [comment]
Have you had similar updating issues with other mods' configs?

**Comment by Methlon** [comment]
Well, I seem to be required now to crown my self king of the morons.
I'd gone through a new install OS upgrade on my linux server, right.. been running the server from the correct directory, but somehow.. my brain failed to register (backup drive) vs (new directory).. I've had us both fighting a version that wasn't in use... woops.  No frickin wonder.. I'll be nuking that folder.  Serves me right for changing partition layout..  Fingers faster than the eye, I twice wound up in same directory rather than the one I kinda needed..

I'm.. going to go hang my head in shame now..
This is a new record of self oversight that may never be topped..
Sadly, I cant pass beer through the monitor, so I can't make up to you the time I wasted.

I .. feel.. tarded.. sorry for the mess, sir..
Had you going all up and over hell's half acre for nothing.

**Comment by The-Fireplace** [comment]
Lmao, I figured it had to be something like that. Glad you got it working.
And if you were serious about wanting to pass me a beer, I do have [a Patreon](https://www.patreon.com/The_Fireplace).
