### ISSUE TITLE
Raid mode invites players

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#164]
Inviting players in raid mode will prompt: you are not in a raid mode
Clan Version 1.5.3
Realization:
/raid join 12344
Tip: successful raid
/raid invite 5555
Tip: you are not in a raid mode
Enter / raid join 12344 again
Tip: you are already in a raid. If you want to continue, you must leave your raid
Unable to join the raid by invitation

**Comment by mcqwy** [comment]
Many people can successfully launch a raid by the following methods
Player A: / raid join 12344
Player B: / raid join 12344
Player A: / raid start
Prompt: the raid was successfully launched

**Comment by The-Fireplace** [comment]
Can you provide your latest.log from when this happens?

**Comment by mcqwy** [comment]
[2020-02-29-3.log](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/4269972/2020-02-29-3.log)

**Comment by The-Fireplace** [comment]
For future reference, please use a site like https://pastebin.com/ when posting logs. I'm looking in to the issue.
