### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#166]
Forge Version 2838
Clan Version 1.5.3
Reproduction method:
Player A executes / raid join 12344
Player A executes / raid start
Then player A exits the game and waits for the raid to begin.
The server crashed.

**Comment by mcqwy** [comment]
Crash log。
https://github.com/mcqwy/Crash-log/blob/master/latest.log

**Comment by mcqwy** [comment]
![image](https://user-images.githubusercontent.com/38318368/75851055-abf44480-5e23-11ea-9708-08e23566c78d.png)
I took a look at your code. Do you need to add this judgment to fix bug?

**Comment by The-Fireplace** [comment]
Thanks for the report, I'll get it fixed ASAP

**Comment by mcqwy** [comment]
I don't know if it's going to break down in any other way,
So I hope you can check all the methods that can be executed into this code.
Your reply, update and repair speed is very fast.
That's why I'm optimistic about this Mod!

**Comment by mcqwy** [comment]
When trying to repair Mod.
Please don't do what I say.
It is wrong, it will affect the normal raid process.
`if(member != null)`

**Comment by The-Fireplace** [comment]
Clans 1.5.6 is released, fixing this crash.

**Comment by mcqwy** [comment]
That is great!
This is comparable to the speed of light repair speed!!!
