### ISSUE TITLE
When using the Clan API, it was found that......

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#167]
I'm doing the affiliated mod development of clan.
I found this when I looked through your source code.
RaidingParties.java
![image](https://user-images.githubusercontent.com/38318368/75889191-7f621c00-5e67-11ea-92df-7348f8533064.png)
`dean.sendMessage(new TextComponentString(">I don’t care about game devs >Devs can suck a dick >Game devs are fucking scum").setStyle(TextStyles.DARK_GREEN).appendSibling(new TextComponentString(" - you, 9/2/2019 10:50-10:51 AM CDT").setStyle(TextStyles.RESET)));`
Is this your prank? ...

Text:
When I try to use the `Raid.getdefenders();` method, it cannot get defensive members

**Comment by The-Fireplace** [comment]
Yes, it is a prank on a specific person, which is why before that it checks for his UUID before doing that. The message is what he said one day, and I disagree with it, which is why I remind him of it then strike him with lightning.
As for the issue with Raid.getDefenders(), what exactly is the problem? Always returning an empty list?

**Comment by mcqwy** [comment]
Yes, it returns an empty list.
At first I thought it was my own mod problem.
Later I tried to add the following code to your source code.
It still returns a null value.
![image](https://user-images.githubusercontent.com/38318368/75895838-27c8ae00-5e71-11ea-80a8-ec8386b34096.png)
However, the lack of a defender can be judged in your raid.
Is my writing method wrong?

**Comment by mcqwy** [comment]
`getRaids().get(raidTarget).getAttackers()` You can get the Raider.
`getRaids().get(raidTarget).getDefenders()` The gained defender is empty.

**Comment by The-Fireplace** [comment]
OK, is this being called before or after the raid starts?

**Comment by The-Fireplace** [comment]
If you are doing it before the raid starts, that explains why it is empty - it can't say for certain who in the clan is going to be online and defending from the raid, which is why the set is empty at that time.

**Comment by The-Fireplace** [comment]
If you need the potential defenders before starting the raid, I suggest using raidTarget.getOnlineMembers()

**Comment by mcqwy** [comment]
Thank you very much for your help!
It works very well now!

**Comment by The-Fireplace** [comment]
Update: Actually looking at it now, you should use raidTarget.getOnlineSurvivalMembers() so it is filtered to the ones that would actually count as defenders when the raid starts.

**Comment by mcqwy** [comment]
Thank you. I see
