### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#168]
Clan Version 1.5.6

Question 1:
Payer A dies without clicking the regenerate button.
Player B makes a raid on player a.
After starting the raid, player a can't find it because he didn't revive.
But the raid is still in progress.

Question 2:
Player A dies without clicking the regenerate button.
Player B makes a raid on player A.
After starting the raid, player a can't find it because he didn't revive.
But the raid is still in progress.
Server use / kick player A
The server crashed.

Question 3:
Industrial machines can be turned on during raids.
Or other mod containers.
This is a very serious problem. Players can steal in this way

**Comment by mcqwy** [comment]
[https://github.com/mcqwy/Crash-log/blob/master/latest.log](url)
Crash log

**Comment by The-Fireplace** [comment]
In the future, please put different questions in different issues.

> Question 1:
> Payer A dies without clicking the regenerate button.
> Player B makes a raid on player a.
> After starting the raid, player a can't find it because he didn't revive.
> But the raid is still in progress.

I am looking in to this, once I figure it out I will release Clans 1.5.7 with a fix.

Question 2:

> Player A dies without clicking the regenerate button.
> Player B makes a raid on player A.
> After starting the raid, player a can't find it because he didn't revive.
> But the raid is still in progress.
> Server use / kick player A
> The server crashed.

I've fixed the crash, I will be releasing the fix with Clans 1.5.7.
Question 3:

> Industrial machines can be turned on during raids.
> Or other mod containers.
> This is a very serious problem. Players can steal in this way

Please report issues with specific mods on separate issues so I know exactly which mods' containers are still able to be accessed. If an issue already exists for a mod and you are having the same problem, just comment there so I know it is still a relevant issue. Different mods will require different fixes, as I have already done what I can to make sure regular containers should be protected.

**Comment by The-Fireplace** [comment]
Update: I'm putting question 1 into a separate issue, it isn't related to the crash and needs further investigation. I am going ahead and releasing 1.5.7 with the crash fix.

**Comment by mcqwy** [comment]
All IC2 machine GUIs can be opened
Industrial storage box included
Projecte:Alchemy box
And players can right-click to take the crops from the crop rack

**Comment by The-Fireplace** [comment]
Please create two new issues, one for IC2 and one for Project E, and provide the requested information about steps to reproduce, mod versions and forge version, etc.
