### ISSUE TITLE
The specified box will not be restored during raid

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#170]
Clan Version 1.5.6
Redstone
Repeater
Carpet
IC2: Crop rack

**Comment by The-Fireplace** [comment]
I just tested restoring Redstone, Repeater, and Carpet after a raid with version 1.6.3 and it appears to work fine. If you test with that version or newer and it is still an issue, please comment and provide more details and I will try to help get it fixed.
