### ISSUE TITLE
You can open the alchemy box of equivalent exchange during the raid

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#173]
Projecte:Alchemy box
Players can open the box and take away the items in the box during the raid
Clan 1.5.6
Forge 2838
ProjectE-1.12.2-PE1.4.1

**Comment by The-Fireplace** [comment]
Test again with Clans 1.5.9, it may have been fixed but I haven't tested with this specific mod.

**Comment by The-Fireplace** [comment]
If you test with a newer version and this is still an issue, comment and I will re-open the issue.
