### ISSUE TITLE
Config option to respawn at clan home

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#175]
Hello,
I'm using a sponge.
Because sponge has nucleus plug-in.
If the player is reborn.
Sponge will send players to the birth point first.
Then, clans will transfer players to their clans.
This will allow players to switch back and forth.
Don't allow players to be reborn in their clans.
Can you add this to the clan profile?

**Comment by The-Fireplace** [comment]
So when a player dies, you want them to have the option to respawn at their clan home?

**Comment by mcqwy** [comment]
Players are reborn in clans.
I want to be able to turn it on or off in clans.cfg.

**Comment by mcqwy** [comment]
If the player can choose.
Then it will lead to the above problems.

**Comment by The-Fireplace** [comment]
I may have done this already with whatever the solution was to #77 . I'll look into it and get back to you.

**Comment by mcqwy** [comment]
You can modify it in the `playerevents.class`.
For example: write like me.
`public static boolean isRebornatclanshome;
    @SubscribeEvent
    public static void onPlayerRespawn(PlayerEvent.PlayerRespawnEvent event) {
        if(isRebornatclanshome = true)
        {
        	PlayerEventLogic.checkUpdateDefaultClan(event.player);
            if(event.player.bedLocation == null)
                PlayerEventLogic.onPlayerRespawn(event.player);
        }
    }`

**Comment by The-Fireplace** [comment]
Ok, so as of right now, if a player doesn't have a bed, they respawn at the clan home. Are you suggesting with a config option I change this to always spawn them at the clan home, even if they have a bed?

**Comment by The-Fireplace** [comment]
Or did you want me to have an option to turn off the being reborn at the clan home?
Based on the code you provided, this is what I will do.

**Comment by mcqwy** [comment]
![image](https://user-images.githubusercontent.com/38318368/76262471-63131480-6297-11ea-8b58-4054be69011b.png)
This is my request.
Can you read it?
Sorry my English is not good, I didn't understand what you said.

**Comment by The-Fireplace** [comment]
Yes, I understand exactly what you are asking now, I'll have it done in a few minutes.

**Comment by mcqwy** [comment]
Thank you very much.
