### ISSUE TITLE
Disable Nucleus /fly command during raid

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#179]
Add a list of disable directives to the configuration file of clan.

**Comment by The-Fireplace** [comment]
Because /fly is not a vanilla command, I'll need to know which plugin you are using that adds it.

**Comment by mcqwy** [comment]
Sponge.
Nucleus-1.14.1-S7.1-MC1.12.2-plugin.

**Comment by mcqwy** [comment]
Can you do this, please?

**Comment by The-Fireplace** [comment]
I will look in to it.

**Comment by mcqwy** [comment]
Thank you

**Comment by The-Fireplace** [comment]
Duplicate of #70
