### ISSUE TITLE
Ice and Fire dragons bypass protection against mobs

### ISSUE THREAD

**Issue by nazzyz** [The-Fireplace-Minecraft-Mods/Clans#182]
This may or may not be an issue with clans but I wanted to post it for awareness.
using iceandfire-1.8.3 (https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
a 3x3 (48x48) square server claim was made at world spawn. My understanding is that claimed land with the appropriate settings should de-spawn mobs when they enter the area. Normal minecraft mobs do follow this rule and work as intended.
During gameplay, a fire dragon wandered into the claimed area due to what I'm assuming was that it detected NPCs and proceeded to torch the spawn base.
The dragon mobs didn't seem to be affected by the de-spawn rule and wanted to note the find here.
(the world was restored to a prior backup, so no permanent harm done (= )

    Minecraft: [1.12.2]
    Mod Version: [Clans-1.12.2-1.5.0]
    Forge (If applicable) [Forge 14.23.5.2838]

**Comment by The-Fireplace** [comment]
I've done what I can to fix this. It isn't perfect, but your claims should be much better protected than before. Untamed creatures from the mod should now be prevented from spawning on claims just like regular mobs, and tamed dragons (mostly) can't destroy things on other clans' claims. I've filed an issue on the Ice and Fire issue tracker asking for events that will allow me to better protect against this happening.
Alex-the-666/Ice_and_Fire#2226

**Comment by The-Fireplace** [comment]
Clans 1.5.10 includes the partial fix.
