### ISSUE TITLE
Ability to disable pvp on the opclan's land

### ISSUE THREAD

**Issue by Kashwar** [The-Fireplace-Minecraft-Mods/Clans#183]
I tried to combine building dungeons and quests with clan wars, but server territories are a source of problems . Players try to kill each other. 

On the server, we solved this problem with the help of command blocks that gave high "protection", which made the players immortal. However, this approach has a number of limitations : command blocks were spammed into the console, and players did not enter the dungeons, since pvp was enabled there.

Placing a player in the clan when logging on to the server also did not solve the problem , because a long list of ID s would have to be added to the list of blocks that the admin can block . Therefore, I ask the developer to add the ability to disable pvp in the opclan's land. It would be ideal to make it possible to create pvp-chunks .

**Comment by The-Fireplace** [comment]
Done in Clans 1.5.10
