### ISSUE TITLE
My server crashes

### ISSUE THREAD

**Issue by Temtatork** [The-Fireplace-Minecraft-Mods/Clans#187]
**Describe the bug**
My server crashes and i dont know why but it seems clans is part of the problem, at least the last release because this didnt happen before (sorry for the crappy english)

https://media.discordapp.net/attachments/682347215263498278/691821060139778160/5.png?width=1092&height=614

**Comment by Temtatork** [comment]
It seems it was actually a grand economy issue, when a clan didnt have enough money to pay, instead of disband, it crashes the game (once again sorry for the crappy english)

**Comment by The-Fireplace** [comment]
No, this appears to be a Clans issue. What does your config look like?

**Comment by The-Fireplace** [comment]
Clans 1.6.1 might fix this, give it a try. At the very least, it should give a more helpful error message when something goes wrong. If the issue still happens, comment and I will re-open the issue
