### ISSUE TITLE
Chunk claiming doesn't take money

### ISSUE THREAD

**Issue by MoHyB123** [The-Fireplace-Minecraft-Mods/Clans#189]
**Describe the bug**
From Version 1.6.3 in Minecraft 1.12.2 it doesn't remove money, even though it it set to take a certain amount of credits. Tried with just Grand Economy or Grand Economy and Ender Pay. Tried a formula or just a number (even 0). 1.5.10 works perfectly.

**To Reproduce**
1. Install Clans and Grand Economy
2. Set clans config for it to cost any amount of money (or put in formula) to claim chunks
3. Create clan and claim chunks
4. Its free and it produces an error (see below)

**Logs/Screenshots/Videos**
It always (no matter what formula or number is used) produces this error:
[clans]: Problem with the configured formula: 0 - does not evaluate to a decimal value

**Versions:**
 - Minecraft: 1.12.2
 - Mod Version: 1.6.3
 - Forge: 14.23.5.2847

**Comment by The-Fireplace** [comment]
Try version 1.6.3 if you haven't already

**Comment by The-Fireplace** [comment]
Oh, I see. Edits don't show up on the email notifications. I'll look in to this when I get back to my desktop and let you know.

**Comment by The-Fireplace** [comment]
I'm having difficulty getting this problem to happen in 1.6.3. I've tried claiming with the default value (0) and I've also tried setting it to 1 and it still seems to work. This probably doesn't have any bearing on the issue but just in case, what Java version are you using?

**Comment by The-Fireplace** [comment]
Also, could you paste the logs on a site such as https://paste.ubuntu.com and provide me a link?

**Comment by MoHyB123** [comment]
Hey, was busy, sorry. Here you go:
https://paste.ubuntu.com/p/PpxYc32Nqt/
Java Version: openjdk version "1.8.0_242"

**Comment by MoHyB123** [comment]
![WhatsApp Image 2020-04-09 at 18 13 28](https://user-images.githubusercontent.com/62671290/78932659-3a558900-7aa8-11ea-9e79-d580e748c9ae.jpeg)

**Comment by The-Fireplace** [comment]
Clans 1.6.7 should fix this. Also, you should probably update Grand Economy for the latest bugfixes for that.
