### ISSUE TITLE
You can only damage hostile/animal mobs inside your own claim.

### ISSUE THREAD

**Issue by apricitypx** [The-Fireplace-Minecraft-Mods/Clans#19]
Weird bug where as soon as I leave my claimed chunks, be it directly into another claim or into the wilderness, I stop doing damage to hostile and friendly mobs. 

I can **_hit_** them, the animation plays and the sound effects do too, but I could stand there and swing for 15 minutes at a single mob.

**Comment by The-Fireplace** [comment]
Fixed in 1.1.4
