### ISSUE TITLE
Potential Bug for Fire, Paintings, and Frames

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Clans#191]
**Describe the bug**
It seems that breaking paintings and taking from item frames is possible with a block breaking permission, as is putting out fires in claimed areas. However, I have only tested this on my server with a decent amount of other mods that may be interfering.

**To Reproduce**
1. Have a player from another clan attempt to put out a fire or steal from an item frame or break a painting.
2. It may be worth mentioning my clan is a server clan, although doubtful that makes a difference

**Logs/Screenshots/Videos**
Logs not relevant.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-1.5.10
 - Forge (If applicable) Latest

**Comment by The-Fireplace** [comment]
To make sure I'm clear on this, you said the ability to break item frames and paintings in others' territories only came when they were granted permission to break blocks in that territory? I just tested, and am unable to do so without permission to break in another clan's territory, just wanted to make sure I'm fully addressing the issue.

**Comment by Hydraheads** [comment]
It seems like it is no longer an issue, for one reason or another. Thank you!
