### ISSUE TITLE
Clan balance wiped every restart

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Clans#195]
**Describe the bug**
Whenever my server closes or restarts, the balance of everyone's clan is set to zero. I was able to repeat this in singleplayer, and even with a freshly generated config file.

**To Reproduce**
Theoretically
1. Deposit funds from Grand Economy to your clan
2. Log off
3. Log back on
4. Funds are gone /c balance
There's a possibility some other mod is messing with it, but that seems less likely.

**Logs/Screenshots/Videos**
[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/4525983/latest.log)
The log more or less shows the output of the /c balance upon relogging.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: Clans 1.6.8, Grand Economy-1.4.1
 - Forge: 14.23.5.2847

**Comment by MoHyB123** [comment]
I had the same Issue. For now we reverted to Grand Economy 1.3.6, because its a GE issue.

**Comment by MoHyB123** [comment]
I had this issue. For now we reverted to Grand Economy 1.3.6. The issue is on GEs side I think

**Comment by MoHyB123** [comment]
Using it together with Enderpay however it does not work either

**Comment by The-Fireplace** [comment]
Fixed in Clans 1.6.9
