### ISSUE TITLE
Server crash on lama spit

### ISSUE THREAD

**Issue by thomasburke121** [The-Fireplace-Minecraft-Mods/Clans#196]
**Describe the bug**
Server crash when lama spit hits a player
**To Reproduce**
Steps to reproduce the behaviour:

1. Get lama
2. Attack lama
3. See error

**Logs/Screenshots/Videos**
https://paste.ubuntu.com/p/TyCjm45pTp/

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-1.6.8.jar
 - Forge 1.12.2 - 14.23.5.2847
-  Tryed server jars Mohist-1.12.2-0175c77-server.jar, Magma Dev master-0e43213

**Comment by The-Fireplace** [comment]
Would you be willing to try this without Mohist or Magma and see if that fixes the issue? If it does, it should probably be reported to them. Regardless, I have a workaround.

**Comment by The-Fireplace** [comment]
Fixed in Clans 1.6.9
