### ISSUE TITLE
Issues with Quark

### ISSUE THREAD

**Issue by omerbadawy11** [The-Fireplace-Minecraft-Mods/Clans#204]
**Describe the bug**
Hello, I messaged you previously on discord under the name Infinitea, my issue is that I cant interact with the totemofholding from Quark which is an entity i assume that stores your items after you die.

**To Reproduce**
https://www.youtube.com/watch?v=heqzz_IRFHU

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-1.6.10
 - Forge (If applicable) 14.23.5.2847

**Comment by The-Fireplace** [comment]
Note to self: You punch the totem of holding to get your stuff.
