### ISSUE TITLE
Permission command.clans.opclan.buildadmin doesn't work

### ISSUE THREAD

**Issue by Tennik** [The-Fireplace-Minecraft-Mods/Clans#205]
Hi. I have an issue with permission node "command.clans.opclan.buildadmin". Seems its doesn't work properly.
I'm using LuckyPerms on my server. I have added that node to some groups and users. I even add that node to Admins group, but still cant use it. I get the nest error: "You dont have a permission to perform that command"
I also tried to add a "command.clans.opclan" node, but still can't use /op commands

 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-1.6.11 (latest)
 - Forge v14.23.5.2854
 - Server core: Spigot+Forge (CatServer)
 - Permission plugin: LuckyPerms

**Comment by The-Fireplace** [comment]
Clans is not currently designed to work with Spigot permission managers, I have just created #208 to track progress on making that happen. If you're having issues right now, odds are something generated base permissions for opclan, clan, and raid commands, so you might check `/lp tree` to see what is there.
