### ISSUE TITLE
Minimap integration

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#21]
As someone on CF suggested, minimap integration for claimed land would be a plus. This would likely require Clans to be loaded on the client side to do the integration, but this client presence could be used for more aesthetic improvements and features in the future. It would be an optional client presence too, so if Clans is not loaded on the client, no harm done, the mod still works as intended.

**Comment by mrdeadlocked** [comment]
Maybe dynmap support also? It could then still be server-side only.

**Comment by The-Fireplace** [comment]
Dynmap support, definitely on my todo list. Note to self: https://gitlab.com/hardrockrealms/mods/warsftbdynmap/tree/master/src/main/java/com/hardrockrealms/warsftbdynmap

**Comment by The-Fireplace** [comment]
Dynmap support has been done for a while now. Support for other map mods likely won't happen unless it can be done on the server side.
