### ISSUE TITLE
Repeated server crash

### ISSUE THREAD

**Issue by omerbadawy11** [The-Fireplace-Minecraft-Mods/Clans#225]
Hello, Hope you're doing great Fireplace
I got an issue and I'm guessing it's clans?
https://hastebin.com/yapenuseli.md
If you would be kind enough to give it a look I'd appreciate it

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-1.6.13
 - forge-14.23.5.2847
 - iceandfire-1.9.1-1.12.2

**Comment by The-Fireplace** [comment]
Update to Clans 2.0.0, it should be fixed.
