### ISSUE TITLE
How to prohibit the installation of blocks, not just their destruction ?

### ISSUE THREAD

**Issue by RadeonRX** [The-Fireplace-Minecraft-Mods/Clans#227]
In the first screenshot, he writes that you cannot install blocks on uninhabited land, because it is protected.
On the second screen, I easily put  
https://drive.google.com/drive/folders/1ZDEYsXo_kCpwTner_Kyj1QEd4cGB0qtO?usp=sharing

**Comment by The-Fireplace** [comment]
What Clans version are you using?

**Comment by RadeonRX** [comment]
> Какую версию кланов вы используете?

Clans-1.12.2-1.6.14

**Comment by RadeonRX** [comment]
> Какую версию кланов вы используете?

Clans-1.12.2-1.6.14 
Server -1.12.2

**Comment by The-Fireplace** [comment]
Try updating to Clans 2.0.0 and let me know if the problem continues to
happen.
