### ISSUE TITLE
Raiding not working properly

### ISSUE THREAD

**Issue by omerbadawy11** [The-Fireplace-Minecraft-Mods/Clans#228]
When I start a raid on my friend I teleport instantly outside his borderlands, but when he starts a raid on me it doesn't teleport him and over time I just win cause he never got here. We both have clan homes set.
Also, if one of us kills the other the raid never ends, it only ends if one person was outside the claim!
so if I raided him and i stayed on the claim for a while and he didn't i win, and if I don't get on time he wins... killing doesn't end the raid no matter how many times I kill him.

**Versions**
 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-2.0.0
 - Forge: forge-14.23.5.2854

**Comment by The-Fireplace** [comment]
Will you make a paste of your logs from when this happens so I can see if anything unusual is there?

**Comment by omerbadawy11** [comment]
Issue seems to be fixed. Thank you ♥
