### ISSUE TITLE
Mass claiming land nukes server TPS in the long term

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Clans#229]
**Describe the bug**
Apparently, the raw quantity of land claims in a server/sp world has a long term impact on server tps, such that every claim made has a very tiny effect on tps. To elaborate, its not so much active tps as it is world saving tps and such. Thus, with a very large amount of server claims, the world's tps may pause every 30 seconds for as much as 10 seconds causing players to be unable to open chests and mobs unable to move. This means claiming large builds for the server or a large radius around spawn could kill the server. It is noticable when the amount of total land claims on the server exceeds perhaps a million or so. /clan map slows down and the tps is lower in general. Effectively, /clan claim 1000 can be the death of a world. 

Perhaps having the claims not being all saved regularly in the way they are would prevent this, or simply let this report be a warning to server owners who have no idea why their servers started dying.

**To Reproduce**
1. Install any version of clans whatsoever
2. Create a singleplayer world and make a server clan
3. Run the command /clan claim 1000
4. Watch as your world file is totally nuked. /clan map now takes 7-10 seconds rather than being instant, and there are massive lag spikes on top of lower tps in general. Only solution is disbanding the clan or nuking its claims.

**Logs/Screenshots/Videos**
Stuff like this begins to appear in the logs regularly after massive land claims.
```
20.06 05:11:12 [Server] Server thread/WARN Something's taking too long! 'root.save' took aprox 2643.923898 ms
20.06 05:11:12 [Server] Server thread/WARN Something's taking too long! 'root' took aprox 2648.352316 ms
20.06 05:11:12 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2709ms behind, skipping 54 tick(s)
20.06 05:11:57 [Server] Server thread/WARN Something's taking too long! 'root.save' took aprox 2551.9739 ms
20.06 05:11:57 [Server] Server thread/WARN Something's taking too long! 'root' took aprox 2567.010151 ms
20.06 05:11:57 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2622ms behind, skipping 52 tick(s)
20.06 05:12:02 [Server] Server thread/WARN Something's taking too long! 'root.connection.jump' took aprox 2049.524819 ms
20.06 05:12:02 [Server] Server thread/WARN Something's taking too long! 'root.connection' took aprox 2050.616 ms
20.06 05:12:02 [Server] Server thread/WARN Something's taking too long! 'root' took aprox 2067.531724 ms
20.06 05:12:43 [Server] Server thread/WARN Something's taking too long! 'root.save' took aprox 2511.632887 ms
20.06 05:12:43 [Server] Server thread/WARN Something's taking too long! 'root' took aprox 2531.562254 ms
20.06 05:12:43 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2653ms behind, skipping 53 tick(s)

```

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Was able to reproduce both pre-2.0 and post 2.0 clans
 - Forge 1.12.2 - 14.23.5.2854

**Comment by The-Fireplace** [comment]
Interestingly enough, it doesn't seem to be saving that's causing the majority of the problems, it's checking for if mobs are allowed to spawn. I'll make some changes in 2.1.0 to help address this.
