### ISSUE TITLE
An unknown error occured while attempting to perform this command

### ISSUE THREAD

**Issue by reidsplosion** [The-Fireplace-Minecraft-Mods/Clans#230]
**Describe the bug**
whenever i type in /clan form (name) it says "An unknown error occured while attempting to perform this command"

**To Reproduce**
1. type /clan form (name)
 i am on a bisect hosting server. the mod is installed in the server and it is installed on the client i am using. i am operator.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: [1.12.2]
 - Mod Version:

Clans-1.12.2-2.0.0
--

reccomended version of forge.
my modpack is https://www.youtube.com/redirect?v=y0faPfjBirk&event=video_description&redir_token=hy8bdGmTrZ65glC-loZ4OPe8dd58MTU5MzU3Mjk0M0AxNTkzNDg2NTQz&q=https%3A%2F%2Fwww.technicpack.net%2Fmodpack%2Freidsmpearth.1712983

i run command at console says this java.lang.NoSuchMethodError: the_fireplace.grandeconomy.api.GrandEconomyApi.takeFromBalance(Ljava/util/UUID;DLjava/lang/Boolean;)Z
29.06 21:10:17 [Server] INFO at the_fireplace.clans.forge.compat.PaymentHandlerGE.deductAmount(PaymentHandlerGE.java:12) ~[PaymentHandlerGE.class:?]
29.06 21:10:17 [Server] INFO at the_fireplace.clans.commands.details.CommandForm.run(CommandForm.java:52) ~[CommandForm.class:?]
29.06 21:10:17 [Server] INFO at the_fireplace.clans.commands.ClanSubCommand.func_184881_a(ClanSubCommand.java:105) ~[ClanSubCommand.class:?]
29.06 21:10:17 [Server] INFO at the_fireplace.clans.commands.CommandClan.func_184881_a(CommandClan.java:219) ~[CommandClan.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
29.06 21:10:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
29.06 21:10:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
29.06 21:10:17 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
29.06 21:10:17 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
29.06 21:10:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

sorry if format bad

**Comment by The-Fireplace** [comment]
Update to Grand Economy 2.0.0, leave a comment if that doesn't fix it and I'll re-open the issue.

**Comment by reidsplosion** [comment]
will do! thank

**Comment by reidsplosion** [comment]
does my client need the clans mod or just the server

**Comment by The-Fireplace** [comment]
Just the server
