### ISSUE TITLE
Fake players do not work in claimed chunks.

### ISSUE THREAD

**Issue by thakyZ** [The-Fireplace-Minecraft-Mods/Clans#231]
**Describe the bug**
Fake players (block placers/breakers) don't work in claimed chunks even with tolerable fake players set to `"*"`.

**To Reproduce**
1. Form clan
2. Claim area
3. Place an open blocks or other block placer and load the block with cobblestone and activate the block with redstone
3. The cobblestone should not be able to be placed.

**Logs/Screenshots/Videos**
Log: https://pastebin.com/N33Ad6tS

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 2.0.1
 - Forge: 14.23.5.2854

**Comment by The-Fireplace** [comment]
What mod adds the fake players in question? And could you repost the log?
