### ISSUE TITLE
API event acquisition

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#233]
Hello, how can I use the clanapi to get the event of player entering town?
Events after a player leaves town and enters the wilderness
Players join the raid event
A raid on an impending event

**Comment by The-Fireplace** [comment]
There isn't currently an easy way to do this. If you make a PR adding an
event, I'll merge it and make a build.

**Comment by mcqwy** [comment]
Hello, I had a problem trying to build clan-1.12.2-2.0.1.
I imported nightconfig-core-3.6.3.jar and built it successfully.
But it crashes when the server starts.
Is this caused by the absence of nightconfig-core-3.6.3.jar at runtime?
Here is the error report section.
[2.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/4988707/2.txt)

**Comment by mcqwy** [comment]
Hi!
It took me a few hours.
Help you to basically complete several event trigger functions.
First, create an event class
`the_fireplace.clans.forge.compat.ClanModEvent`
`public class ClanModEvent {
	
	public static final EventBus EVENT_BUS = new EventBus();
	
	/**
	 * Please do not add too much calculation code in this time, otherwise it may cause the server to be stuck
	 * @author clan
	 *
	 */
	@Cancelable
    public static class PlayerNewRaidEvent extends net.minecraftforge.event.entity.player.PlayerEvent
    {
		public final EntityPlayer player;
        public final String clanname;
        public PlayerNewRaidEvent(EntityPlayer player, String ClanName) {
			super(player);
			this.player = player;
			this.clanname = ClanName;
		}
    }
	
	/**
	 * Please do not add too much calculation code in this time, otherwise it may cause the server to be stuck
	 * @author clan
	 *
	 */
	@Cancelable
    public static class PlayerRaidStartAfterEvent extends net.minecraftforge.event.entity.player.PlayerEvent
    {
		public final EntityPlayer player;
		public final List<UUID> attacker;
        public final List<UUID> defender;
        public final String clanname;
        public PlayerRaidStartAfterEvent(EntityPlayer player,List<UUID> att,List<UUID> def, String ClanName) {
			super(player);
			this.player = player;
			this.attacker = att;
			this.defender = def;
			this.clanname = ClanName;
		}
    }
	
	/**
	 * Please do not add too much calculation code in this time, otherwise it may cause the server to be stuck
	 * @author clan
	 *
	 */
	@Cancelable
    public static class PlayerRaidStopEvent extends net.minecraftforge.event.entity.player.PlayerEvent
    {
		public final EntityPlayer player;
        public final String clanname;
        public final boolean raiderVictory;
        public PlayerRaidStopEvent(EntityPlayer player,boolean raiderVictory,String clanname) {
			super(player);
			this.player = player;
			this.raiderVictory = raiderVictory;
			this.clanname = clanname;
		}
    }
	
	/**
	 * Please do not add too much calculation code in this time, otherwise it may cause the server to be stuck
	 * Type 1 = field, type 2 = underground, type 3 = clanname. If the types are 1 and 2, the clanname and the leadername are null
	 * @author clan
	 *
	 */
	@Cancelable
    public static class handleTerritoryChangedMessageEvent extends net.minecraftforge.event.entity.player.PlayerEvent
    {
		public final EntityPlayer player;
        public final String clanname;
        public final int type;
        public final String leadername;
        public handleTerritoryChangedMessageEvent(EntityPlayer player, int type, String clanname,String leadername) {
			super(player);
			this.player = player;
			this.clanname = clanname;
			this.type = type;
			this.leadername = leadername;
		}
    }
}
`

**Comment by mcqwy** [comment]
``

**Comment by mcqwy** [comment]
Hi!
I spent some time defining a few events.
First create event class' ClanModEvent.java '
[ClanModEvent.java.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/5004247/ClanModEvent.java.txt)

on stay 'Clans.java' register
Register in `public void init(FMLInitializationEvent event)` method
`new ClanModEvent();`
You can publish any custom events to forge through forge method, and others can handle things directly by listening to events when developing attached mod.
Example of publishing event: `MinecraftForge.EVENT_BUS.post(event);`

Calling methods and publishing events.
There are players forming a new raid team event.
[CommandJoinRaid.java.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/5004263/CommandJoinRaid.java.txt)

Start the raid Event.
[CommandStartRaid.java.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/5004271/CommandStartRaid.java.txt)

End Raid Event.
[RaidingParties.java.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/5004275/RaidingParties.java.txt)

handleTerritoryChangedMessageEvent.
[TimerLogic.java.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/5004277/TimerLogic.java.txt)

The above are some of the events and ideas I provided.
More custom events you can refer to my ideas to write code.
The above code I only tested part of the event, maybe there will be bugs, maybe there will be a better place to write.
You can change it as you like.
