### ISSUE TITLE
Cancel /clan home secure transfer detection

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#234]
From 1.5.6, my server players have been having similar problems because they don't pay attention.
The current version of 2.0.1 will still result in the inability to use `/c h`to send home.
I hope you can add in the configuration file: cancel security transfer configuration item.
If the player's teleport point is blocked, they will be teleported to other places.
And I didn't install the satellite map mod, which would make them unable to find their home.
Secure transfer also prevents the administrator who created the pattern from using the `/oc tp [clan]` command

**Comment by mcqwy** [comment]
Hello, it suddenly occurred to me,
You can enter `/clan home` after.
Judge whether they are blocked. If they are blocked, send them to the clans boundary and prompt their home location to be blocked.

**Comment by The-Fireplace** [comment]
The issue with clan homes being blocked will be fixed in version 2.1.0. The issue was with the way I was teleporting them, so putting them to the claim boundary wouldn't have helped.
