### ISSUE TITLE
NPC mod, players cannot interact with it

### ISSUE THREAD

**Issue by mcqwy** [The-Fireplace-Minecraft-Mods/Clans#236]
Clan-2.0.1
Sponge-7.2.3-2838
Players cannot interact with NPCs in the server's clans.

**Comment by The-Fireplace** [comment]
Which NPC mod? Please provide a link, and the version you are using.

**Comment by mcqwy** [comment]
CustomNPCs_1.12.2-(01Oct19).jar

**Comment by mcqwy** [comment]
http://www.kodevelopment.nl/minecraft/customnpcs

**Comment by NoMoreUsernames999** [comment]
Update to a newer version of custom NPC's. I'm using (05jul20) and players can interact with NPCs on server clans just fine.
