### ISSUE TITLE
Server crashes every time I try and start it

### ISSUE THREAD

**Issue by penguin-101** [The-Fireplace-Minecraft-Mods/Clans#246]
The server crashes every time I try to launch it and I believe this mod is causing the issue

**Logs/Screenshots/Videos**

[crash-2021-02-21_20.59.16-server.txt](https://github.com/The-Fireplace-Minecraft-Mods/Clans/files/6019116/crash-2021-02-21_20.59.16-server.txt)

 - Minecraft: 1.12.2
 - Mod Version: Clans-1.12.2-2.1.3
 - Forge (If applicable): 14.23.5.2855

**Comment by The-Fireplace** [comment]
For the moment you can work around the issue by disabling Dynmap. This is a Clans issue, from the looks of it I'd guess you probably claimed a large number of chunks and it's having difficulty efficiently turning that into something Dynmap can display.

Also, in the future please follow the instructions given in the template, it makes investigating the issue easier.
![image](https://user-images.githubusercontent.com/5914284/108654422-4105a880-748e-11eb-9079-366b1b19fd34.png)

**Comment by penguin-101** [comment]
Any ETA on when this will be on this will be fixed

**Comment by The-Fireplace** [comment]
No ETA yet, I will probably have to rewrite a good chunk of the Dynmap compat to avoid this. I'll get it fixed when I can.

**Comment by The-Fireplace** [comment]
Workaround added in 2.1.5
