### ISSUE TITLE
Disabled PvP clans do not disable pvp

### ISSUE THREAD

**Issue by cutethingg** [The-Fireplace-Minecraft-Mods/Clans#247]
As the title says. I'll bring you through the steps to replicate: 

- Created a clan
- claimed land
- set it as a server clan

PvP still worked at this point so I did the `/opclan set <clan> <option> <value>` command to disable pvp

- console gives output that clan pvp is now set to default
- pvp still works inside clan borders

This is version 2.1.3.

**Comment by The-Fireplace** [comment]
I need the specific version, not just "latest version". If I release updates then look at this again in the future it is no longer the "latest version", and I've had people claim latest version not realizing that updates have been released since last time they checked.

**Comment by cutethingg** [comment]
Sorry, version 2.1.3.

**Comment by The-Fireplace** [comment]
It appears to work for me.
Just to confirm, 
1.  You're in claimed land, not borderland or wilderness
2. The clan is a server clan
3. The PVP override is either default or 0, not 1

**Comment by The-Fireplace** [comment]
4. Injury Protection is enabled in the config
