### ISSUE TITLE
Cannot public unlock interact blocks

### ISSUE THREAD

**Issue by NOID38** [The-Fireplace-Minecraft-Mods/Clans#249]
**Description**
Blocks that players should be able to interact with after using "/clan lock open" are not able to be interacted with. Currently this applies to crafting tables, anvils, enchanting tables, ender chests. All other 'interactable block are responsive to "/clan lock open".
Blocks that work: Dispensers, chests, hoppers, droppers, trapped chests, jukebox's, chests, furnaces, etc.

**To Reproduce**

1. Place crafting table or anvil etc.
2. use "/clan lock open" on block
3. error message comes up and non clan members cannot use block. 

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft 1.12.2
 - Clans: 1.6.8
 - Forge-1.12.2-14.23.5.2854

**Comment by The-Fireplace** [comment]
Have you tried with Clans 2.1.3?

**Comment by NOID38** [comment]
I added the blocks I wanted to be able to open to the Clans config list! That did the job, thank you!
