### ISSUE TITLE
Industrial Foregoing Plant Sower/Gatherer

### ISSUE THREAD

**Issue by Nightshade93** [The-Fireplace-Minecraft-Mods/Clans#25]
The Plant Sower and Plant Gatherer from Industrial Foregoing are not able to function with claimed chunks. I am using version Clans-1.12.2-1.1.5.jar.

**Comment by Nightshade93** [comment]
The Plant Sower and Plant Gatherer from Industrial Foregoing are not able to function with claimed chunks. I am using version Clans-1.12.2-1.1.5.jar.

**Comment by The-Fireplace** [comment]
Superseded by #65
