### ISSUE TITLE
No permissions listed/granted for setting clan options

### ISSUE THREAD

**Issue by cutethingg** [The-Fireplace-Minecraft-Mods/Clans#250]
Version 2.1.3

As the leader of a clan, I attempted to set the interact option to ANY using this command:
`/clan set interact ANY`
This gave me the response:
`You do not have permission to use this command`

So, I attempted to use `/lp verbose on` to find the specific permission being used, since the given permission on the curseforge site (command.clans.clan.set) is already given to the rank I was currently on. Running the command with `/lp verbose` gave me no response other than the no permission warning. 

Trying the `/lp verbose command [player] clan set interact any` told me that the command execution was completed, but no permission checks were made. Hopefully this is helpful.

EDIT:
Trying to set the permission using `/clan set interact ANY` breaks *all* permissions for Clans including land claim and animal protection. A server restart is required to fix the broken permissions.

**Comment by The-Fireplace** [comment]
This is probably related to #254. I'm closing it for now since that is fixed, re-open if the problem persists.
