### ISSUE TITLE
I'm sorry, but you dont have the permissions to perform this command

### ISSUE THREAD

**Issue by FLORIAN4600** [The-Fireplace-Minecraft-Mods/Clans#251]
Hy, i have a problem with Clans mod.

when i try tu use one of the Clans command (example: /clan help, /c form MyClanName or other commands) the game say: I'm sorry, but you dont have the permissions to perform this command.

I had tryed to use a permission plugin (PexEx,PermissionEx,LuckPerm) but nothing change i had this "error" message.

I had added all the clans permission to the basic permission i had give to myself the basic permission to be sure, but nothing changed.

I dont know what is the problem.

The mod is in a server.

The server is aternos (aternos.org)

The minecraft version of the server is Magma 1.12.2 vad7ca54-CUSTOM

The java version of the server is Java 8

The version of the mod is Clans-1.12.2-2.1.3.jar

And the current version of my permission plugin is LuckPerms-Bukkit-5.3.47.jar

**Comment by FLORIAN4600** [comment]
I can use the commands only when i am an operator with the /op vanilla command.

**Comment by The-Fireplace** [comment]
Try using the LuckPerms command to see what permissions are being checked when using a command. I think it's `/lp verbose`. You'll want to do that then try `/clan form <name>` and see what permission it is missing.

**Comment by FLORIAN4600** [comment]
thanks to you for your quick responce

I had make the command and that work.

the curseforge explication of the mod say the permission is:command.clans.clan but the real permission is: commandclan.clan

I realy thank you

**Comment by The-Fireplace** [comment]
commandclan.clan is not added by me. Different permission mods/plugins will sometimes add their own permissions to go along with the ones I have posted on CurseForge, and there's nothing I can do to control it.
