### ISSUE TITLE
opclan claim blocked by clan home exclusion.

### ISSUE THREAD

**Issue by NOID38** [The-Fireplace-Minecraft-Mods/Clans#252]
**Description**
When trying to use /opclan claim (clan-a) within the initial claim separation exclusion range of (clan-b) an error message saying "you cannot claim this chunk of land because it is too close to another clan's home." comes up and you cannot claim. 

**To Reproduce**
1. create clan-a
2. claim chunk for clan-a
3. create clan-b and claim a chunk within the exclusion range
4. See warning "you cannot claim this chunk of land because it is too close to another clan's home..."

**Versions**
 - Minecraft: 1.12.2
 - Mod Version: 1.6.8
 - Forge: 14.23.5.2854

**Comment by The-Fireplace** [comment]
Will be fixed in 2.1.4
