### ISSUE TITLE
Clan mutlichunk Claiming ignores Dimension Whitelist

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Clans#258]
**Describe the bug**
 You can mass claim land in non-whitelist dimension by typing /clan claim (number) instead of /clan claim. It simply ignores the dimension settings.

**To Reproduce**
1. Type /clan claim 5 or any number in another dimension.
2. Regardless of settings, that land in any dimension is now claimed.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 2.1.4, but this has been around since early 2.0 versions I believe
 - Forge 14.23.5.2885

**Comment by The-Fireplace** [comment]
Fixed in 2.1.5
