### ISSUE TITLE
Borderlands Persist when Disabled

### ISSUE THREAD

**Issue by Hydraheads** [The-Fireplace-Minecraft-Mods/Clans#259]
**Describe the bug**
Clan borderlands remain if you enabled them once and disabled them later, and are very hard to get rid without disbanding clans or opclaim. I guess this one would be hard to fix without performance issues, but it would be nice to have opclan claim in other dims to get rid of borderlands in the end or other dims that were claimed, or maybe opclan unclaim working on borderlands, or preferably a command that clears current borderlands one time so it doesn’t impact performance with constant checks.

**To Reproduce**
1. Enable Borderlands in the config
2. Load up world
3. Disable Borderlands in the config
4. Load up world again

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 2.1.4, but this has been around since early 2.0 versions I believe
 - Forge 14.23.5.2885

**Comment by The-Fireplace** [comment]
Don't worry about performance on this one. I expect it'll be possible to fix without any problems or a workaround like having to use a command.

**Comment by The-Fireplace** [comment]
Fixed in 2.1.5
