### ISSUE TITLE
Clans with 'Ice and Fire' mod crash

### ISSUE THREAD

**Issue by thejbone** [The-Fireplace-Minecraft-Mods/Clans#260]
**Describe the bug**
Crash due to 
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/api/event/DragonFireEvent

**To Reproduce**
1. Install Ice and Fire 1.7.1 (RLCraft)
2. Install Clans
3. Error crash

**Logs/Screenshots/Videos**
https://pastebin.com/ivdsUYC4

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: [e.g. 2.0.1]
 - Forge: Forge 14.23.5.2855

**Comment by The-Fireplace** [comment]
Update to Ice and Fire 1.9.1
