### ISSUE TITLE
Unable to get clan rent to work. 

### ISSUE THREAD

**Issue by NoMoreUsernames999** [The-Fireplace-Minecraft-Mods/Clans#262]
**Describe the bug**
I have enabled clan rent, have grand economy installed, and have set the rent amount to 1.5*c once a day. Using clan info I can see the amount the rent is and how much players will be charged. However players don't get charged and the clan account doesn't loose money once a day. 

**To Reproduce**
Set up a clan.
Use above values. 
Wait 2 IRL days (only really feasible on a server). 
Check values of clan and player accounts. They remain the same. 
 
**Versions**
 - Minecraft: 1.12.2
 - Mod Version: 2.1.4
 - Forge: 14.23.5.2854 (I know it's not the latest version, but 2855 is incompatible with a number of other mods).

**Comment by The-Fireplace** [comment]
Thank you for the details, I'm looking in to it.

**Comment by The-Fireplace** [comment]
Can you reproduce this now and post a debug log here after running it for a day or two?

**Comment by The-Fireplace** [comment]
Also, the output of `/clan details` and any other related info you have on the rent setup.
