### ISSUE TITLE
Claiming Territory in Modded Dimensions

### ISSUE THREAD

**Issue by liffley** [The-Fireplace-Minecraft-Mods/Clans#265]
**Is your feature request related to a problem? Please describe.**
I cannot claim land in modded dimensions

**Describe the solution you'd like**
Allowing the claiming of land in modded dimensions 

**Additional contex
![2022-01-25_15 20 06](https://user-images.githubusercontent.com/98283988/151006200-b7e25d74-46a0-4f00-9075-192f29dcf79e.png)**

**Comment by The-Fireplace** [comment]
There is a config option that controls which dimensions you can claim in. Either add the dimensions you want, or remove the defaults and add "*" and any dimensions you don't want to allow claims in.

**Comment by The-Fireplace** [comment]
If you've messed with this option and still have problems, comment and I can re-open the issue

**Comment by liffley** [comment]
Where would I be able to find the config options??

**Comment by The-Fireplace** [comment]
In the Clans config file, it's called `clans.conf` and should be in your config folder.
