### ISSUE TITLE
More visible clan details

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#28]
This should include:
- [x] Clan description shows when you enter clan territory
- [x] View all players in clan details, not just online
- [x] See player info: What clans they are in
- [x] Ability to list all clans on a server

**Comment by mrdeadlocked** [comment]
Being able to list all clans on a server would be great as well.

**Comment by The-Fireplace** [comment]
Added it to the list.
