### ISSUE TITLE
Crash with Dynmap

### ISSUE THREAD

**Issue by JonMaker050** [The-Fireplace-Minecraft-Mods/Clans#38]
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * Provide the Forge version you experienced the issue with. Do *not* say "latest" for this, provide the actual version number.
 * Provide the mod version you experienced the issue with. Do *not* say "latest" for this, provide the actual version number.
 * For any issue, providing your client and/or server logs can be helpful in geting the issue solved quickly. These are usually named something like latest.log, debug.log, fml-client-latest.log, or fml-server-latest.log and can be found in the logs folder. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and link it here. If you have latest.log and debug.log, please provide both.
 * If you crashed, please paste the crash log to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and link it here.

**Comment by JonMaker050** [comment]
Minecraft 1.12.2

Forge 2822

https://pastebin.com/yp3Rmm4A

**Comment by JonMaker050** [comment]
Clans Version 1.12.2-1.2.2

Dynmap Version 3.0 Beta 3 Forge

**Comment by The-Fireplace** [comment]
Fixed in Clans 1.2.3
