### ISSUE TITLE
Blockplacer Entity on Protected Land

### ISSUE THREAD

**Issue by SnorrLaxZ** [The-Fireplace-Minecraft-Mods/Clans#49]
Forge | 1.12.2 | 14.23.5.2836
Clans | 1.12.2 | 1.2.3

As title says, when using a block placer from "Industrial Foregoing" on a claimed land it resulted in an instant crash, aswell as instant crash on re-entering the server.

https://pastebin.com/68zRVmrL

**Comment by zellfrey** [comment]
The Industrial Foregoing Plant sower does not crash in this version. However when it attempts to place a sapling or seed you can hear the planting sound but nothing appears & the plant sowers inventory remains the same



Clans-1.12.2-1.2.5
GrandEconomy-1.12.2-1.0.1

Forge version :1.12.2-14.23.5.2781

**Comment by The-Fireplace** [comment]
I have a plan to fix this, but the reason it does that right now is to
prevent people from using blocks to place things in other clans' territory.
My initial plan is a blanket fix that will use a config option to allow
them  (and many other modded machines) to work on claimed land.

**Comment by zellfrey** [comment]
Thats fine, just had to check so I wouldn't need to tell players not to place specific blocks in clans
