### ISSUE TITLE
Creating a new clan, 3 bugs

### ISSUE THREAD

**Issue by zellfrey** [The-Fireplace-Minecraft-Mods/Clans#53]
1. `/clan form CLANNAME` doesn't work and returns the message: `/clan [clan] <command> [parameters]`. However `/clan create CLANNAME` works fine

2. When a clan is formed, the player receives the message `Clan formed!` followed with `CLANNAME has been disbanded due to inability to pay upkeep costs`. This doesnt affect anything as the clan is still intact.

**EDIT:**
3. If a town has been disbanded and a new clan is created near the previous town, the home coordinates of the previous town persist preventing the new town from claiming the chunks in that area. A server restart seems to fix this issue  

Clans-1.12.2-1.2.4
GrandEconomy-1.12.2-1.0.1

Forge version :1.12.2-14.23.5.2781

**Comment by The-Fireplace** [comment]
In the future, please make three separate issues when you have three separate issues.
