### ISSUE TITLE
Suggestion: Quality of life improvements for invitation commands

### ISSUE THREAD

**Issue by zellfrey** [The-Fireplace-Minecraft-Mods/Clans#56]
Did abit of testing on my server. Currently we feel there isn't enough feedback when it comes to executing certain commands, in this case invitation commands. 
Here is what we came up with:

`/clan invite <player>` 

- When a player logs in, its sends them a message of pending invites they have received

- If a player has a pending invite and another clan tries to invite them, it should send a message to the player that another town has tried to invite them. Equally it should send the requester a message that the target player already has a pending invite.

- Or a player can get a list of pending invites and can view them with a command like `/clan pending` and that player can cycle through those invites with the usual `/clan decline` & `/clan accept`

`/clan decline` 
- Would be QoL to message leader(s) of the town that member has declined invitation

`/clan accept` 
- Would be QoL to message players of town that member has joined

`/clan leave` 
- Would be QoL to message players of town that member has left

`/clan kick`
- Would be QoL to message players  or only leaders of town that member has been kicked

Clans-1.12.2-1.2.5
GrandEconomy-1.12.2-1.0.1

Forge version :1.12.2-14.23.5.2781

**Comment by The-Fireplace** [comment]
All of these are doable except for one small detail: Pending invites don't get stored permanently, they just remain until a player logs out. Because they aren't stored, you also can't invite offline players to clans, and there are never pending invites waiting for a player when they log in.
