### ISSUE TITLE
Suggestion: Modules to enable disable raiding / currency

### ISSUE THREAD

**Issue by luxlacis** [The-Fireplace-Minecraft-Mods/Clans#64]
Just a simple feature to enable and disable raids and currency entirely.

**Comment by The-Fireplace** [comment]
See #61 about the total disabling of raids. As for currency, setting the costs to zero or simply not using Grand Economy will do that.

**Comment by The-Fireplace** [comment]
Update: Actually looking at the config, all the currency related options are set to 0 by default, so even with Grand Economy installed, you'd still have to configure Clans to enable currency.
