### ISSUE TITLE
Suggestion: Land Claiming Visual

### ISSUE THREAD

**Issue by kreezxil** [The-Fireplace-Minecraft-Mods/Clans#68]
I don't expect your mod to be like grief prevention. But grief prevention which is a spigot plugin that runs well server side can show the boundaries of what is being claimed and subdivided as seen in the following video. 

[![](https://img.youtube.com/vi/I3FLCFam5LI/0.jpg)](https://www.youtube.com/watch?v=I3FLCFam5LI)

Perhaps something like that can be done too.

**Comment by The-Fireplace** [comment]
Perhaps a new command to do things similar to Factions, /clan seechunk [on|off] which would allow you to see the borders of the chunk you are in automatically when walking if you use the [on], otherwise would just show the chunk you are currently in.

**Comment by kreezxil** [comment]
I need to get away from FTB Utilities claiming system and a visual
representation with your mod would go a long way in doing that. While you
are at it make it compatible with Journeymap such that journeymap will show
claims on both it's minimap and world map. Journeymap has the capability
already as it does show FTB Utilities claims.
