### ISSUE TITLE
Server Will Not Load and Just Crashes With Dynmap

### ISSUE THREAD

**Issue by dmh3333** [The-Fireplace-Minecraft-Mods/Clans#74]
There are a lot of mods present, so hopefully it isn't an issue with one of those, however, it looks like an issue with Dynmap Compat or something.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.43 (1).jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/11/19 11:48 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at the_fireplace.clans.clan.ClanChunkCache.clansWithClaims(ClanChunkCache.java:33)
	at the_fireplace.clans.compat.dynmap.DynmapCompat.initializeMap(DynmapCompat.java:149)
	at the_fireplace.clans.compat.dynmap.DynmapCompat.onServerTickEvent(DynmapCompat.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_867_DynmapCompat_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2380261760 bytes (2269 MB) / 6442450944 bytes (6144 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 3 total; -Xmx12G -Xms6G -XX:+UseG1GC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 110 mods loaded, 110 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version              | Source                                          | Signature                                |
	|:------ |:-------------------------------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2               | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp                                          | 9.42                 | minecraft.jar                                   | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99            | server.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2838         | server.jar                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore                                |                      | minecraft.jar                                   | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                      | minecraft.jar                                   | None                                     |
	| LCHIJA | appliedenergistics2                          | rv6-stable-4         | appliedenergistics2-rv6-stable-4.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | quark                                        | r1.5-130             | Quark-r1.5-130.jar                              | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-20               | AutoRegLib-1.3-20.jar                           | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJA | bdlib                                        | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                    | None                                     |
	| LCHIJA | buildcraftlib                                | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftcore                               | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftbuilders                           | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftenergy                             | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftfactory                            | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftrobotics                           | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcrafttransport                          | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | buildcraftsilicon                            | 7.99.18              | buildcraft-7.99.18.jar                          | None                                     |
	| LCHIJA | carryon                                      | 1.7.2                | CarryOn+MC1.12.2+v1.7.2.jar                     | None                                     |
	| LCHIJA | cfm                                          | 4.2.0                | cfm-4.2.0-mc1.12.2.jar                          | None                                     |
	| LCHIJA | codechickenlib                               | 3.2.2.353            | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks                                | 2.4.1.71             | ChickenChunks-1.12.2.jar                        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | dynmap                                       | 3.0-beta-4-213       | Dynmap-3.0-beta-4-forge-1.12.2.jar              | None                                     |
	| LCHIJA | grandeconomy                                 | 1.1.2                | GrandEconomy-1.12.2-1.1.2.jar                   | None                                     |
	| LCHIJA | clans                                        | 1.2.10               | Clans-1.12.2-1.2.10.jar                         | None                                     |
	| LCHIJA | redstoneflux                                 | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore                                     | 4.6.1                | CoFHCore-1.12.2-4.6.1.22-universal.jar          | None                                     |
	| LCHIJA | cofhworld                                    | 1.3.0                | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | compactmachines3                             | 3.0.12               | compactmachines3-1.12.2-3.0.12-b215.jar         | None                                     |
	| LCHIJA | computercraft                                | 1.80pr1              | ComputerCraft1.80pr1.jar                        | None                                     |
	| LCHIJA | crafttweaker                                 | 4.1.11               | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| LCHIJA | mantle                                       | 1.12-1.3.3.39        | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| LCHIJA | endercore                                    | 1.12.2-0.5.43        | EnderCore-1.12.2-0.5.43 (1).jar                 | None                                     |
	| LCHIJA | jei                                          | 4.8.5.151            | jei_1.12.2-4.8.5.151.jar                        | None                                     |
	| LCHIJA | thermalfoundation                            | 2.6.1                | ThermalFoundation-1.12.2-2.6.1.22-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion                             | 5.5.2                | ThermalExpansion-1.12.2-5.5.2.39-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | enderio                                      | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiointegrationtic                        | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.11.0.106    | TConstruct-1.12.2-2.11.0.106.jar                | None                                     |
	| LCHIJA | conarm                                       | 1.2.0.1              | conarm-1.12.2-1.2.0.1.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | extendedrenderer                             | v1.0                 | coroutil-1.12.1-1.2.11.jar                      | None                                     |
	| LCHIJA | coroutil                                     | 1.12.1-1.2.11        | coroutil-1.12.1-1.2.11.jar                      | None                                     |
	| LCHIJA | configmod                                    | v1.0                 | coroutil-1.12.1-1.2.11.jar                      | None                                     |
	| LCHIJA | crafttweakerjei                              | 2.0.2                | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342           | movingworld-1.12-6.342-full.jar                 | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@        | davincisvessels-1.12-6.340-full.jar             | None                                     |
	| LCHIJA | enderiobase                                  | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduits                              | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics            | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsopencomputers                 | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage                | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | ic2                                          | 2.8.79-ex112         | industrialcraft-2-2.8.79-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | natura                                       | 1.12.2-4.3.2.62      | natura-1.12.2-4.3.2.62.jar                      | None                                     |
	| LCHIJA | forestry                                     | 5.8.2.369            | forestry_1.12.2-5.8.2.369.jar                   | None                                     |
	| LCHIJA | enderiointegrationforestry                   | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiointegrationticlate                    | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiomachines                              | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderiopowertools                            | 5.0.39               | EnderIO-1.12.2-5.0.39.jar                       | None                                     |
	| LCHIJA | enderstorage                                 | 2.4.5.135            | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | shetiphiancore                               | 3.5.8                | shetiphiancore-1.12.0-3.5.8.jar                 | None                                     |
	| LCHIJA | endertanks                                   | 1.6.6                | endertanks-1.12.0-1.6.6.jar                     | None                                     |
	| LCHIJA | energyconverters                             | 1.2.0.10             | energyconverters_1.12.2-1.2.0.10.jar            | None                                     |
	| LCHIJA | immersiveengineering                         | 0.12-86              | ImmersiveEngineering-0.12-86.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | engineersdoors                               | 0.8.0                | engineers_doors-1.12.2-0.8.0.jar                | None                                     |
	| LCHIJA | valkyrielib                                  | 1.12.2-2.0.18.3      | valkyrielib-1.12.2-2.0.18.3.jar                 | None                                     |
	| LCHIJA | environmentaltech                            | 1.12.2-2.0.18.2      | environmentaltech-1.12.2-2.0.18.2.jar           | None                                     |
	| LCHIJA | extrautils2                                  | 1.0                  | extrautils2-1.12-1.7.6.jar                      | None                                     |
	| LCHIJA | zerocore                                     | 1.12-0.1.2.2         | zerocore-1.12-0.1.2.2.jar                       | None                                     |
	| LCHIJA | bigreactors                                  | 1.12.2-0.4.5.49      | ExtremeReactors-1.12.2-0.4.5.49.jar             | None                                     |
	| LCHIJA | foamflower                                   | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar             | None                                     |
	| LCHIJA | forgemultipartcbe                            | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe                                | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | None                                     |
	| LCHIJA | minecraftmultipartcbe                        | 2.6.0.79             | ForgeMultipart-1.12.2-2.6.0.79-universal.jar    | None                                     |
	| LCHIJA | galacticraftcore                             | 4.0.1.181            | GalacticraftCore-1.12.2-4.0.1.181.jar           | None                                     |
	| LCHIJA | galacticraftplanets                          | 4.0.1.181            | Galacticraft-Planets-1.12.2-4.0.1.181.jar       | None                                     |
	| LCHIJA | waila                                        | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHIJA | immersivepetroleum                           | 1.1.9                | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
	| LCHIJA | instantunify                                 | 1.1.2                | instantunify-1.12.2-1.1.2.jar                   | None                                     |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.34.820    | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| LCHIJA | jeibees                                      | 0.9.0.5              | jeibees-0.9.0.5-mc1.12.2.jar                    | None                                     |
	| LCHIJA | mrtjpcore                                    | 2.1.3.35             | MrTJPCore-1.12.2-2.1.3.35-universal.jar         | None                                     |
	| LCHIJA | netherportalfix                              | 5.3.17               | NetherPortalFix_1.12.1-5.3.17.jar               | None                                     |
	| LCHIJA | oreexcavation                                | 1.4.118              | OreExcavation-1.4.118.jar                       | None                                     |
	| LCHIJA | projectred-core                              | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-Base.jar             | None                                     |
	| LCHIJA | projectred-compat                            | 1.0                  | ProjectRed-1.12.2-4.9.1.92-compat.jar           | None                                     |
	| LCHIJA | projectred-integration                       | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| LCHIJA | projectred-transmission                      | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-integration.jar      | None                                     |
	| LCHIJA | projectred-fabrication                       | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-fabrication.jar      | None                                     |
	| LCHIJA | projectred-illumination                      | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-lighting.jar         | None                                     |
	| LCHIJA | projectred-expansion                         | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| LCHIJA | projectred-relocation                        | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| LCHIJA | projectred-transportation                    | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-mechanical.jar       | None                                     |
	| LCHIJA | projectred-exploration                       | 4.9.1.92             | ProjectRed-1.12.2-4.9.1.92-world.jar            | None                                     |
	| LCHIJA | radixcore                                    | 1.12.x-2.2.1         | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| LCHIJA | reborncore                                   | 3.10.4.348           | RebornCore-1.12.2-3.10.4.348-universal.jar      | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | rustic                                       | 0.4.8                | rustic-0.4.8.jar                                | None                                     |
	| LCHIJA | stevescarts                                  | 2.4.24.118           | StevesCarts-1.12.2-2.4.24.118.jar               | None                                     |
	| LCHIJA | tesla                                        | 1.0.63               | Tesla-1.12.2-1.0.63.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | thermalcultivation                           | 0.3.1                | ThermalCultivation-1.12.2-0.3.1.8-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics                              | 2.5.3                | ThermalDynamics-1.12.2-2.5.3.16-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thutperms                                    | 2.1.12@              | thutpermissions-1.12.2-2.1.12.jar               | None                                     |
	| LCHIJA | treechopper                                  | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| LCHIJA | valkyriecompat                               | 1.12.2-2.0.18.1      | valkyriecompat-1.12.2-2.0.18.1.jar              | None                                     |
	| LCHIJA | universalmodifiers                           | 1.12.2-1.0.16.1      | valkyrielib-1.12.2-2.0.18.3.jar                 | None                                     |
	| LCHIJA | vending                                      | 1.12.2-3.0.1.2       | vending-1.12.2-3.0.1.2.jar                      | None                                     |
	| LCHIJA | wanionlib                                    | 1.12.2-1.8           | WanionLib-1.12.2-1.8.jar                        | None                                     |
	| LCHIJA | wearablebackpacks                            | 3.1.2                | WearableBackpacks-1.12.2-3.1.2.jar              | None                                     |
	| LCHIJA | industrialwires                              | 1.7-31               | IndustrialWires-1.7-31.jar                      | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCHIJA | unidict                                      | 1.12.2-2.9.1         | UniDict-1.12.2-2.9.1.jar                        | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.43 (1).jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	AE2 Version: stable rv6-stable-4 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-4.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.5-130.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.49.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.18.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.18.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.18.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.18.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.1.22-universal.jar
		* ComputerCraft|API (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|FileSystem (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Lua (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Media (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Network (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Peripheral (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Permissions (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Redstone (1.80pr1) from ComputerCraft1.80pr1.jar
		* ComputerCraft|API|Turtle (1.80pr1) from ComputerCraft1.80pr1.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.12.1-1.2.11.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.2.20.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.39.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.369.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.369.jar
		* Galacticraft API (1.1) from GalacticraftCore-1.12.2-4.0.1.181.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-86.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-86.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.151.jar
		* projectred|api (2.0) from ProjectRed-1.12.2-4.9.1.92-Base.jar
		* QuarkAPI (2) from Quark-r1.5-130.jar
		* reborncoreAPI (3.10.4.348) from RebornCore-1.12.2-3.10.4.348-universal.jar
		* reborncoreAPI|Power (3.10.4.348) from RebornCore-1.12.2-3.10.4.348-universal.jar
		* reborncoreAPI|Recipe (3.10.4.348) from RebornCore-1.12.2-3.10.4.348-universal.jar
		* reborncoreAPI|Tile (3.10.4.348) from RebornCore-1.12.2-3.10.4.348-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* stevescartsAPI (${version}) from StevesCarts-1.12.2-2.4.24.118.jar
		* stevescartsAPI|FARMS (${version}) from StevesCarts-1.12.2-2.4.24.118.jar
		* valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.18.3.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.2.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.10.4.348
		Runtime Debofucsation 1
	Ender IO: No known problems detected.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:ON, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by The-Fireplace** [comment]
Yeah, this is my fault. I'll get it fixed today when I get home from work.

**Comment by The-Fireplace** [comment]
Fixed in 1.2.11. Also, please use pastebin.com or paste.ubuntu.com in the future when posting crash reports.
