### ISSUE TITLE
More opclan commands

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#8]
Allow OPs to promote, demote, or kick other clans' members, disband other clans, and edit other clans' names and descriptions.

**Comment by Boomflex** [comment]
Allow OP to give credits via command

/oc deposit <Username> <Credit Amount>

**Comment by The-Fireplace** [comment]
I can add
/oc deposit <clan name> <Credit Amount>
There's already a command included in Grand Economy for ops to give players money.
