### ISSUE TITLE
QoL improvements for /clan home

### ISSUE THREAD

**Issue by The-Fireplace** [The-Fireplace-Minecraft-Mods/Clans#88]
maximOP on Discord:
Also should make the countdown for /clan home  show up in chat, and also if you move or get hit, it cancels it. Because the whole point of the delay is so that a player cant just tele home in combat, being able to move while teleporting far away to safety is kind of overpowered

**Comment by baronjutter** [comment]
Great idea.  On Lost Shard there is a "recall" system that functioned very much the same.  A long cooldown use between uses and about a 10-second countdown, but the countdown would display but be interrupted if you moved or were hit in combat.  It was often quite tense waiting in some hiding place while the countdown happened not knowing if you'd escape in time or not.
